spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8001/postgres
    username: admin
    password: admin
  application:
    name: Administration
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8788"
  cloud:
    config:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/ADT-Validation-documents
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 2345
app:
  key_cloak:
    realm: ADT-Validation-documents
    baseUrl: http://localhost:8000
    auth: ${app.key_cloak.baseUrl}/auth/realms/${app.key_cloak.realm}/protocol/openid-connect/token
    users: ${app.key_cloak.baseUrl}/auth/admin/realms/${app.key_cloak.realm}/users
    clients: ${app.key_cloak.baseUrl}/auth/admin/realms/${app.key_cloak.realm}/clients
    client_id: microservice-administration
    client_secret: 36088666-047f-44d6-a1d4-8a8370a704db
  entities:
    default:
      admin:
        email: admin@gmail.com
        password: admin
        firstName: admin
        lastName: admin
        phoneNumber: 06********
  constants:
    transaction-limit-per-day: 10
    document-max-size-MB: 10
    client-app-transaction-limit-per-day: 14
    client-app-document-max-size-MB: 14
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
   # path: swagger-ui/index.html
    operationsSorter: method