spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8001/postgres
    username: admin
    password: admin
  application:
    name: Administration
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: "configserver:http://localhost:8788"
  cloud:
    config:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/ADT-Validation-documents
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 2345
app:
  key_cloak:
    realm: ADT-Validation-documents
    baseUrl: http://localhost:8000
    auth: ${app.key_cloak.baseUrl}/auth/realms/${app.key_cloak.realm}/protocol/openid-connect/token
    users: ${app.key_cloak.baseUrl}/auth/admin/realms/${app.key_cloak.realm}/users
    client_id: microservice-administration
    client_secret: eadbdaae-35f2-4ec7-90a5-1f74e7935fa9 
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
   # path: swagger-ui/index.html
    operationsSorter: method