package ma.adria.document_validation.administration.model.enums;

import lombok.Getter;

@Getter
public enum ErrorCode {
	ACCOUNT_USER_NOT_FOUND_ID,
	ADT_CONST_NOT_FOUND_ID,
	ADT_CONST_NOT_FOUND_CODE,
	ACCOUNT_USER_NOT_FOUND,
	ACCOUNT_USER_OLD_PASSWORD_MISSING,
	ACCOUNT_USER_NEW_PASSWORD_MISSING,
	ACCOUNT_USER_OLD_PASSWORD_INCORRECT,
	ACCOUNT_USER_RESET_OLD_PASSWORD_MATCH
}
